name: Create Releases And Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu,aarch64-unknown-linux-gnu

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-build"
          cache-on-failure: true

      - name: Run tests
        run: cargo test --verbose --release --all-features --jobs $(nproc)
        
      - name: Build all targets
        run: |
          cargo build --verbose --release --target x86_64-unknown-linux-gnu --jobs $(nproc)
          sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu
          cargo build --verbose --release --target aarch64-unknown-linux-gnu --jobs $(nproc) --config target.aarch64-unknown-linux-gnu.linker=\"aarch64-linux-gnu-gcc\"

      - name: Strip binaries
        run: |
          strip target/x86_64-unknown-linux-gnu/release/quoterm
          aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/quoterm

      - name: Archive source code as tar.gz
        run: |
          mkdir -p target/source
          git archive --format=tar.gz -o target/source/quoterm-${{ github.ref_name }}.tar.gz HEAD

      - name: Archive source code as zip
        run: |
          mkdir -p target/source
          git archive --format=zip -o target/source/quoterm-${{ github.ref_name }}.zip HEAD

      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ''
          draft: false
          prerelease: false

      - name: Upload x86_64-unknown-linux-gnu binary to GitHub release
        id: upload-x86_64-linux
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/release/quoterm
          asset_name: quoterm-x86_64-unknown-linux-gnu
          asset_content_type: application/octet-stream

      - name: Upload aarch64-unknown-linux-gnu binary to GitHub release
        id: upload-aarch64-linux
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/aarch64-unknown-linux-gnu/release/quoterm
          asset_name: quoterm-aarch64-unknown-linux-gnu
          asset_content_type: application/octet-stream

      - name: Upload tar.gz source archive to GitHub release
        id: upload-source-targz
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/source/quoterm-${{ github.ref_name }}.tar.gz
          asset_name: quoterm-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload zip source archive to GitHub release
        id: upload-source-zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: target/source/quoterm-${{ github.ref_name }}.zip
          asset_name: quoterm-${{ github.ref_name }}.zip
          asset_content_type: application/zip

  build-macos:
    needs: build-linux
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "release-build"
          cache-on-failure: true

      - name: Build all targets
        run: |
          cargo build --verbose --release --target x86_64-apple-darwin --jobs $(sysctl -n hw.ncpu)
          cargo build --verbose --release --target aarch64-apple-darwin --jobs $(sysctl -n hw.ncpu)

      - name: Strip binaries
        run: |
          strip target/x86_64-apple-darwin/release/quoterm
          strip target/aarch64-apple-darwin/release/quoterm

      - name: Upload x86_64-apple-darwin binary to GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build-linux.outputs.upload_url }}
          asset_path: target/x86_64-apple-darwin/release/quoterm
          asset_name: quoterm-x86_64-apple-darwin
          asset_content_type: application/octet-stream

      - name: Upload aarch64-apple-darwin binary to GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.build-linux.outputs.upload_url }}
          asset_path: target/aarch64-apple-darwin/release/quoterm
          asset_name: quoterm-aarch64-apple-darwin
          asset_content_type: application/octet-stream
